github: [your-github-username]
patreon: your-patreon-username
ko_fi: your-ko-fi-username
buy_me_a_coffee: your-buymeacoffee-username
open_collective: your-opencollective-username
custom: ["https://your-custom-donation-link.com"]
